name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy services
        run: |
          cd /home/dannv/docker-apps/novuservice
          if [ ! -f .env ]; then
            cp .env.example .env
            echo "Copied .env.example to .env"
          else
            echo ".env file already exists"
          fi
          docker-compose pull
          docker-compose up -d